kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: training-test-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: dynamic
spec:
  storageClassName: dynamic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi