apiVersion: v1
kind: Template
metadata:
  name: hello
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hello
    name: hello
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hello
      deploymentconfig: hello
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: hello
    name: hello
  spec:
    replicas: 2
    selector:
      app: hello
      deploymentconfig: hello
    template:
      metadata:
        labels:
          app: hello
          deploymentconfig: hello
      spec:
        containers:
        - image: ${REGISTRY}/${NAMESPACE}/hello
          name: hello
          ports:
          - containerPort: 8080
            protocol: TCP
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - hello
        from:
          kind: ImageStreamTag
          name: hello:latest
          namespace: ${NAMESPACE}
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: hello
    name: hello
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: hello
parameters:
- description: The namespace where ImageStreams reside
  name: NAMESPACE
  required: true
- description: The internal docker registry
  name: REGISTRY
  required: false
  value: <integrated-docker-registry>
