apiVersion: v1
kind: Template
metadata:
  name: names
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: names
    name: names
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: names
      deploymentconfig: names
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: names
    name: names
  spec:
    replicas: 1
    selector:
      app: names
      deploymentconfig: names
    template:
      metadata:
        labels:
          app: names
          deploymentconfig: names
      spec:
        containers:
        - image: ${REGISTRY}/${NAMESPACE}/names
          name: names
          ports:
          - containerPort: 8080
            protocol: TCP
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - names
        from:
          kind: ImageStreamTag
          name: names:latest
          namespace: ${NAMESPACE}
      type: ImageChange
parameters:
- description: The namespace where ImageStreams reside
  name: NAMESPACE
  required: true
- description: The internal docker registry
  name: REGISTRY
  required: false
  value: <integrated-docker-registry>
